export const MATCHES_SYNC = 'MATCHES_SYNC';
export const MATCHES_SELECT_MATCH = 'MATCHES_SELECT_MATCH';
export const MATCHES_ADD_MATCH = 'MATCHES_ADD_MATCH';
export const MATCHES_DELETE_MATCH = 'MATCHES_DELETE_MATCH';
export const MATCHES_UPDATE_MATCH = 'MATCHES_UPDATE_MATCH';